# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: bitnami/minio:latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - run: /opt/bitnami/scripts/minio/run.sh & yarn test:coverage
      env:
        CI: true
        MINIO_ACCESS_KEY: "access-mock-key"
        MINIO_SECRET_KEY: "secret-mock-key"
        MINIO_PORT_NUMBER: 9000
        ENDPOINT: "http://localhost:9000"
        ACCESS_KEY: "access-mock-key"
        SECRET_KEY: "secret-mock-key"

