# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nodejs 10

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: yarn install

  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: "access-mock-key"
          MINIO_SECRET_KEY: "secret-mock-key"
          MINIO_PORT_NUMBER: 9000
        ports:
          - 9000:9000
        options: --health-cmd "curl localhost:9000" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: yarn test
        env:
          CI: true
          ENDPOINT: "http://localhost:9000"
          ACCESS_KEY: "access-mock-key"
          SECRET_KEY: "secret-mock-key"


